// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0CVYbBONFb_WWKl2gvPs8OmGk09LmUVE',
    appId: '1:828760448128:web:shopzone',
    messagingSenderId: '828760448128',
    projectId: 'shopzone-f097f',
    authDomain: 'shopzone-f097f.firebaseapp.com',
    storageBucket: 'shopzone-f097f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CVYbBONFb_WWKl2gvPs8OmGk09LmUVE',
    appId: '1:828760448128:android:db70871f5bd7ba0e3a1a65',
    messagingSenderId: '828760448128',
    projectId: 'shopzone-f097f',
    storageBucket: 'shopzone-f097f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0CVYbBONFb_WWKl2gvPs8OmGk09LmUVE',
    appId: '1:828760448128:ios:shopzone',
    messagingSenderId: '828760448128',
    projectId: 'shopzone-f097f',
    storageBucket: 'shopzone-f097f.firebasestorage.app',
    iosBundleId: 'com.example.shopzone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0CVYbBONFb_WWKl2gvPs8OmGk09LmUVE',
    appId: '1:828760448128:macos:shopzone',
    messagingSenderId: '828760448128',
    projectId: 'shopzone-f097f',
    storageBucket: 'shopzone-f097f.firebasestorage.app',
    iosBundleId: 'com.example.shopzone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0CVYbBONFb_WWKl2gvPs8OmGk09LmUVE',
    appId: '1:828760448128:windows:shopzone',
    messagingSenderId: '828760448128',
    projectId: 'shopzone-f097f',
    authDomain: 'shopzone-f097f.firebaseapp.com',
    storageBucket: 'shopzone-f097f.firebasestorage.app',
  );
}
